[package]
name = "josekit"
version = "0.6.0"
description = "JOSE (Javascript Object Signing and Encryption) library for Rust."
repository = "https://github.com/hidekatsu-izuno/josekit-rs"
readme = "README.md"
license = "MIT OR Apache-2.0"
authors = ["Hidekatsu Izuno <hidekatsu.izuno@gmail.com>"]
keywords = ["jose", "jwt", "jws", "jwe", "jwa"]
categories = ["authentication"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
anyhow = "1"
once_cell = "1"
regex = "1"
serde_json = { version = "1", features = ["preserve_order"] }
base64 = "0.12"
flate2 = "1.0"
chrono = "0.4"
openssl = "0.10"
openssl-sys = "0.9"
foreign-types = "0.3.1"

[dev-dependencies]
doc-comment = "0.3.3"
